-- D1 schema for the coffee & tea site.
-- Apply with: wrangler d1 execute coffee-tea-db --file=./db/schema.sql --remote
-- (drop --remote to apply to the local dev database instead)

CREATE TABLE IF NOT EXISTS products (
  id            TEXT PRIMARY KEY,          -- e.g. crypto.randomUUID() generated by the Worker
  category      TEXT NOT NULL CHECK (category IN ('coffee', 'tea')),
  name          TEXT NOT NULL,
  origin        TEXT,                      -- e.g. "Yirgacheffe, Ethiopia"
  process       TEXT,                      -- coffee: washed/natural/honey. tea: withered/oxidized/etc.
  roast_level   TEXT,                      -- coffee only: light/medium/dark. Null for tea.
  leaf_type     TEXT,                      -- tea only: black/green/oolong/white/pu-erh/herbal. Null for coffee.
  caffeine_level TEXT,                     -- tea only: none/low/medium/high. Null for coffee.
  altitude_m    INTEGER,                   -- growing altitude, meters (nice coffee-nerd data point)
  flavor_notes  TEXT,                      -- free text, comma-separated tasting notes
  description   TEXT,
  price_cents   INTEGER NOT NULL,          -- store money as integer cents, never floats
  currency      TEXT NOT NULL DEFAULT 'PHP',
  stock_count   INTEGER NOT NULL DEFAULT 0,
  weight_grams  INTEGER,                   -- for shipping calculations later
  image_key     TEXT,                      -- R2 key, e.g. images/{id}.webp
  thumb_key     TEXT,                      -- R2 key, e.g. images/{id}-thumb.webp
  active        INTEGER NOT NULL DEFAULT 1, -- 1 = visible on public site, 0 = hidden/draft
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_active ON products(active);

CREATE TABLE IF NOT EXISTS sessions (
  token       TEXT PRIMARY KEY,            -- opaque random token, not a JWT (simpler, revocable)
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at  TEXT NOT NULL
);

-- Newsletter email capture (the popup on the public site writes here).
-- Sending campaigns is NOT wired up; that needs an email provider (e.g.
-- Resend, Mailchannels) added as a secret + a send route. This table is
-- just the capture + list side, which is real today.
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  email          TEXT PRIMARY KEY,
  subscribed_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Sample rows so the site and admin dashboard have something to render
-- against right away. Safe to delete once real products are added.
-- Prices are in PHP (pesos), sized to be plausible for the Philippine
-- specialty coffee/tea market, not just the old USD cents relabeled.
INSERT OR IGNORE INTO products
  (id, category, name, origin, process, roast_level, altitude_m, flavor_notes, description, price_cents, currency, stock_count, weight_grams, active)
VALUES
  ('sample-coffee-1', 'coffee', 'Yirgacheffe Sample Lot', 'Yirgacheffe, Ethiopia', 'washed', 'light', 1900,
   'jasmine, bergamot, stone fruit', 'A bright, floral single-origin. Placeholder copy, replace with the client''s real description.',
   65000, 'PHP', 24, 340, 1),
  ('sample-tea-1', 'tea', 'High Mountain Oolong Sample', 'Nantou, Taiwan', 'partially oxidized', NULL, 1200,
   'orchid, toasted rice, honey', 'A gently oxidized oolong. Placeholder copy, replace with the client''s real description.',
   55000, 'PHP', 15, 100, 1);
